version: '3.8'

services:
  web:
    build: backend
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_management_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  pgdata:
